
### docker-compose.yml
version: '3.8'

services:
  prn232-assignment1-api:
    build: .
    container_name: prn232-assignment1-api
    restart: always
    ports:
      - "5291:5291"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5291
    command: ["dotnet", "PRN232_Assignment1.dll"]
